name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying on Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: 🧶 Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
